
services:
  db:
    image: bitnamilegacy/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

  smtp:
    image: ghusta/fakesmtp
    ports:
      - "2525:25"


  ollama:
    image: ollama/ollama:latest
    container_name: ollama_ia
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
  # ---------------------------------

  webserver:
    build: .
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      - DATASOURCE_JNDI
      - DATASOURCE_NAME
      - DB_USER
      - DB_PASS
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - WILDFLY_ADMIN_PASSWORD
      - POSTGRES_DRIVER_VERSION
      - OLLAMA_API_URL=http://ollama:11434/api/generate
      - OLLAMA_MODEL=llama3.2:3b

    depends_on:
      - db
      - smtp
      - ollama


volumes:
  ollama_data: